CRAZYFLIE_BASE := ../../../crazyflie-firmware

EXTRA_CFLAGS += -I$(PWD)/../../inc
EXTRA_CFLAGS += -I$(PWD)/../../decawave_api
EXTRA_CFLAGS += -Wno-error


OOT_CONFIG := $(PWD)/app-config

include $(CRAZYFLIE_BASE)/tools/make/oot.mk

